covert-encryption/covert

covert/cli.py
covert/util.py

Switch to standard Base64 due to less problematic charset, and to make Covert armoring harder to fingerprint. Line lengths are also now randomized.
Armored blocks are, on console, printed between triple-backticks, which mark a codeblock on most messaging systems. The backticks are not part of the message and may be pasted or left out.

Backtick codeblock

---

covert/archive.py
covert/cli.py
covert/pubkey.py
covert/util.py

- Improved randomness of padding size with very small files
- Files in the gigabyte class get slightly less padding (no strict cap)
- Print the randomised padding size on encryption CLI

Implement smarter adaptive padding

---

covert/cryptoheader.py
covert/elligator.py
covert/pubkey.py
docs/Security.md
docs/Specification.md

Without this someone holding many Covert files could assert that they contain encrypted data because of two deterministic bits of information per file. Now every bit is random.

Elligator2 hashing to scramble the ephemeral key header field.

---

covert/__main__.py
covert/cli.py
covert/cryptoheader.py
covert/passphrase.py
docs/Specification.md

Argon2 takes the place of *prehashing* which now gets performed after Argon2. This offers various performance benefits and much simpler implementation. The Argon2 parameters also received further tuning, avoiding insanely long hashing for 8-character passwords.
Threaded password hashing implemented for CLI to minimise any delays seen by user.

New password hashing spec and implementation, and related cleanup.

---

covert/cli.py
covert/util.py

Also other minor changes on util functions.

Refactor armor functions to use str and removing any `>` quotes.

---

covert/__main__.py
covert/cli.py
covert/passphrase.py
covert/tty.py
setup.py

Issue terminal control commands instead of printing ANSI codes on Windows.
Fix #6

Compatibility with legacy Windows terminals

---

covert/__main__.py
tests/asdf.py
tests/test_cli.py

Instead of giving mode separately like `-e '-Arrp` you can now just use `-eArrp`.

Allow mode selecting within combined short arguments.

---

covert/__main__.py
covert/blockstream.py
covert/passphrase.py
tests/test_cli.py

Made the main function always sys.exit() - NoReturn - and with different exit status code for different errors. Cleaned up the CLI tests by implementing a helper fixture 'covert', that calls the main function.

Minor cleanup of CLI main

---

covert/cli.py
tests/test_cli.py

A better diagnostic when `-r github:username` is used, because only `-R github:username` is accepted. The strings given to `-r` are generally regarded untrusted, so we don't want to allow them to make any Internet connections. `-R` takes filenames too, so its inputs must be properly validated anyway.

Improve CLI error messages and testing

---

covert/__main__.py
covert/archive.py
covert/cli.py
covert/passphrase.py
covert/tty.py
covert/util.py
tests/test_cli.py

Implements `covert edit` CLI command that extracts an existing archive, allows editing its text and then re-encrypts the data. Any attached files of the archive are kept without extracting them or the message to disk. The original file is overwritten.
This function is intended to allow adding and removing attachments, as well as using public keys, but for now it is limited to message editing and passphrases. Also, all data must fit in RAM, as no streaming is yet implemented for this mode.
Fixes #57

Support editing archives, keeping encrypted notes

---

covert/elliptic/__init__.py
covert/elliptic/ed.py
covert/elliptic/elligator.py
covert/elliptic/mont.py
covert/elliptic/scalar.py
tests/test_elliptic.py

Improved low order point encoding that is now inconsistent with libsodium and monocypher but more logical and able to represent all low order points correctly. The point at infinity is encoded as u=-1 (mod p), which is not a curve point and has no birational mapping to Ed25519 anyway (division by zero), while everything else uses the standard mapping and encoding specified in RFCs. Similarly the Ed25519 neutral element (ZERO, equivalent to the point at infinity) cannot use birational equivalency as it too causes division by zero due to its y coordinate being 1.

Added Montgomery module and minor changes in Elliptic module

---

covert/blockstream.py
tests/test_blockstream.py

- The blockstream `pos` variable was not updated correctly in some special cases, in particular with files slightly above 1024 bytes.
- Added test for such case.
- Removed unused filelen and filepos variables.
- Don't guess initial nextlen, use block0's known size.
Fix #79

Fix blockstream decryption bug causing signature verification failures

---

setup.py

Upgrade show-in-file-manager to get upstream bugfix for missing dependency that was causing Covert GUI not to start on some systems.

Upgrade dependencies to avoid a problem with GUI not starting

---

covert/__main__.py

"covert enc --help" prints more comprehensive help for encryption options.
"covert dec --help" was fixed to not print encryption options.
"covert edit" pattern matching was corrected. "covert e" would be interpreted as "covert edit", but this conflicts with "covert enc".
"covert [-h] [--help]" prints short help that fits on 80x24 terminal.
"covert help" subcommand prints full help, including supported key formats and command line examples.

List supported key formats and examples in usage

---

covert/__main__.py
covert/blockstream.py
covert/cli.py
covert/clihelp.py
covert/cryptoheader.py
covert/idstore.py
covert/passphrase.py
covert/path.py
covert/ratchet.py
covert/tty.py
docs/Specification.md
setup.py
tests/test_cli.py
tests/test_ratchet.py
tox.ini

Covert needs persistent keystore to avoid always typing keys on command line and more importantly to enable forward secrecy in conversations (because temporary keys need to be stored somewhere).
This is a draft implementation that still contains bugs ~~and does not implement anything but static keys.~~
```fish
covert enc -I alice:bob -i ~/.ssh/id_ed25519 -R github:bob   # Encrypt a message, store keys in database
covert enc -I alice:bob   # Encrypt another message using the stored keys
```
If the sender profile (alice) does not exist, it will be created. If no `-i` is provided, a new keypair is created. Keys may be replaced later by providing another recipient or `-i` arguments. It is planned that bob won't need to add alice's key when replying. In near future this should also enable a …

Implement ID store in a file

---

covert/cli/dec.py
tests/test_cli.py

- Fallback to passphrase if no master ID passphrase is given
- Better error message on wrong master ID passphrase or other errors
- Skip ID store if -p is used to indicate passphrase-encrypted message

Improve covert dec UX with passphrases and ID store

---

covert/idstore.py
covert/ratchet.py
tests/test_ratchet.py

Continuation of the work in #81.
TODO:

Second phase of ID store implementation

---

covert/blockstream.py
covert/cli/__main__.py
covert/cli/dec.py
covert/cli/enc.py
covert/exceptions.py
covert/pubkey.py
tests/test_cli.py

- Uses the newly added additional exception types, minor changes to prior PR
- CLI exit status codes are a bit more specific, numbers changed
- CLI prints the help and exits with status 1 on invalid argument values
- Tests changed accordingly

Improved error handling and diagnostics

---

covert/passphrase.py

Covert would generate a passphrase if a very weak password was input, dismissing the bad password, which was confusing. Now the prompt only accepts either an empty input or a valid password.

Fix handling of weak password input in TTY

---

covert/blockstream.py
covert/gui/decrypt.py

The GUI was not updated properly for 0.7 release and is not up to date with CLI. This PR patches one of the issues, allowing basic GUI use until it can be properly synced with CLI functionality.
Notably missing are idstore and forward secrecy functionality.

Quick fix to GUI not being able to open files.
